/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:35:50 GMT 2018
 */

package com.rac021.jax.api.manager;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rac021.jax.api.manager.IDto;
import com.rac021.jax.api.manager.ResourceManager;
import java.util.List;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ResourceManager_ESTest extends ResourceManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResourceManager resourceManager0 = new ResourceManager();
      resourceManager0.decOffset(3788);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResourceManager resourceManager0 = new ResourceManager();
      Class<Integer> class0 = Integer.class;
      List<IDto> list0 = resourceManager0.executeSQLQuery((EntityManager) null, "", 0, class0, (List<String>) null);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ResourceManager resourceManager0 = new ResourceManager();
      Class<String> class0 = String.class;
      List<IDto> list0 = resourceManager0.executeSQLQuery((EntityManager) null, "b", 0, class0, (List<String>) null);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ResourceManager resourceManager0 = new ResourceManager();
      Class<Object> class0 = Object.class;
      List<IDto> list0 = resourceManager0.executeSQLQuery((EntityManager) null, (String) null, 0, class0, (List<String>) null);
      assertEquals(0, list0.size());
  }
}
