/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:38:14 GMT 2018
 */

package com.rac021.jax.api.interceptor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.rac021.jax.api.interceptor.PoweredByResponseFilter;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerResponseContext;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PoweredByResponseFilter_ESTest extends PoweredByResponseFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PoweredByResponseFilter poweredByResponseFilter0 = new PoweredByResponseFilter();
      ContainerRequestContext containerRequestContext0 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      ContainerResponseContext containerResponseContext0 = mock(ContainerResponseContext.class, new ViolatedAssumptionAnswer());
      poweredByResponseFilter0.filter(containerRequestContext0, containerResponseContext0);
  }
}
