/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:38:34 GMT 2018
 */

package com.rac021.jax.api.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rac021.jax.api.exceptions.BusinessException;
import com.rac021.jax.api.exceptions.BusinessExceptionMapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BusinessExceptionMapper_ESTest extends BusinessExceptionMapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BusinessExceptionMapper businessExceptionMapper0 = new BusinessExceptionMapper();
      BusinessException businessException0 = new BusinessException("");
      // Undeclared exception!
      try { 
        businessExceptionMapper0.toResponse(businessException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }
}
