/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:37:39 GMT 2018
 */

package com.rac021.jax.api.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rac021.jax.api.exceptions.BusinessException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BusinessException_ESTest extends BusinessException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BusinessException businessException0 = new BusinessException(">lEHzq3]l?>]q;");
      BusinessException businessException1 = new BusinessException(">lEHzq3]l?>]q;", businessException0);
      assertFalse(businessException1.equals((Object)businessException0));
  }
}
