/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:36:39 GMT 2018
 */

package com.rac021.jax.api.crypto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rac021.jax.api.crypto.AcceptType;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AcceptType_ESTest extends AcceptType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AcceptType[] acceptTypeArray0 = AcceptType.values();
      assertEquals(7, acceptTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AcceptType acceptType0 = AcceptType.valueOf("JSON_PLAIN");
      assertEquals(AcceptType.JSON_PLAIN, acceptType0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AcceptType acceptType0 = AcceptType.toAcceptTypes("TEMPLATE_ENCRYPTED");
      assertEquals(AcceptType.TEMPLATE_ENCRYPTED, acceptType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      try { 
        AcceptType.toAcceptTypes((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         //  AcceptType [  NULL ] not supported ! 
         //
         verifyException("com.rac021.jax.api.crypto.AcceptType", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      try { 
        AcceptType.toAcceptTypes(":5S4>H@2KPFHF3G[O~");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         //  AcceptType  [ :5S4>H@2KPFHF3G[O~ ] not supported ! 
         //
         verifyException("com.rac021.jax.api.crypto.AcceptType", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      List<AcceptType> list0 = AcceptType.toList((List<String>) null);
      assertNull(list0);
  }
}
