/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:34:05 GMT 2018
 */

package com.rac021.jax.api.crypto.algos;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rac021.jax.api.crypto.EncDecRyptor;
import com.rac021.jax.api.crypto.algos.Des;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Des_ESTest extends Des_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._256;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, (String) null);
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Encrypt;
      des0.setOperationMode(encDecRyptor__Operation0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.CBC;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._64;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "dofinal");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Encrypt;
      des0.setOperationMode(encDecRyptor__Operation0);
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.update;
      byte[] byteArray0 = des0.process("B6'H9#Zfa,ay|9", encDecRyptor__CipherOperation0);
      assertNotNull(byteArray0);
      assertEquals(8, byteArray0.length);
      assertArrayEquals(new byte[] {(byte) (-88), (byte) (-81), (byte) (-31), (byte) (-117), (byte)14, (byte)39, (byte)39, (byte)16}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.CBC;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._64;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "F;*");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Encrypt;
      des0.setOperationMode(encDecRyptor__Operation0);
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.update;
      byte[] byteArray0 = des0.process("F;*", encDecRyptor__CipherOperation0);
      assertEquals(0, byteArray0.length);
      assertNotNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.CBC;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._64;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "F;*");
      byte[] byteArray0 = des0.getIvBytesEncoded64();
      assertNotNull(byteArray0);
      assertEquals(12, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._128;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "");
      byte[] byteArray0 = des0.getIvBytesEncoded64();
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._128;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "");
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.update;
      byte[] byteArray0 = des0.process("", encDecRyptor__CipherOperation0);
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._192;
      Des des0 = new Des((EncDecRyptor._CIPHER_MODE) null, encDecRyptor__CIPHER_SIZE0, "DES");
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.update;
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Decrypt;
      des0.setOperationMode(encDecRyptor__Operation0);
      byte[] byteArray0 = des0.process("DES", encDecRyptor__CipherOperation0);
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._128;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "");
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.dofinal;
      byte[] byteArray0 = des0.process("", encDecRyptor__CipherOperation0);
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._128;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Decrypt;
      des0.setOperationMode(encDecRyptor__Operation0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.CBC;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._64;
      Des des0 = new Des(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "oDb6_");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Decrypt;
      des0.setOperationMode(encDecRyptor__Operation0);
  }
}
