/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:37:11 GMT 2018
 */

package com.rac021.jax.api.streamers;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rac021.jax.api.streamers.EmptyPojo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmptyPojo_ESTest extends EmptyPojo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmptyPojo emptyPojo0 = new EmptyPojo();
      emptyPojo0.setName("~");
      String string0 = emptyPojo0.getName();
      assertEquals("~", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EmptyPojo emptyPojo0 = new EmptyPojo();
      emptyPojo0.setName("");
      String string0 = emptyPojo0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EmptyPojo emptyPojo0 = new EmptyPojo();
      String string0 = emptyPojo0.getName();
      assertNull(string0);
  }
}
