/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:33:44 GMT 2018
 */

package com.rac021.jax.api.crypto.algos;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rac021.jax.api.crypto.EncDecRyptor;
import com.rac021.jax.api.crypto.algos.Desede;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Desede_ESTest extends Desede_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._96;
      Desede desede0 = new Desede(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, (String) null);
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Decrypt;
      desede0.setOperationMode(encDecRyptor__Operation0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._192;
      Desede desede0 = new Desede(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "com.rac021.jax.api.crypto.EncDecRyptor$_Operation");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Encrypt;
      desede0.setOperationMode(encDecRyptor__Operation0);
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.dofinal;
      byte[] byteArray0 = desede0.process("", encDecRyptor__CipherOperation0);
      assertEquals(8, byteArray0.length);
      assertNotNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.CBC;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._256;
      Desede desede0 = new Desede(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "s");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Encrypt;
      desede0.setOperationMode(encDecRyptor__Operation0);
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.update;
      byte[] byteArray0 = desede0.process("_192", encDecRyptor__CipherOperation0);
      assertNotNull(byteArray0);
      assertEquals(0, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.CBC;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._192;
      Desede desede0 = new Desede(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "y]L8n");
      byte[] byteArray0 = desede0.getIvBytesEncoded64();
      assertNotNull(byteArray0);
      assertEquals(12, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._256;
      Desede desede0 = new Desede(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "n1Q");
      byte[] byteArray0 = desede0.getIvBytesEncoded64();
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.CBC;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._192;
      Desede desede0 = new Desede(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "y]L8n");
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.dofinal;
      byte[] byteArray0 = desede0.process("y]L8n", encDecRyptor__CipherOperation0);
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._192;
      Desede desede0 = new Desede((EncDecRyptor._CIPHER_MODE) null, encDecRyptor__CIPHER_SIZE0, "");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Decrypt;
      desede0.setOperationMode(encDecRyptor__Operation0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.ECB;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._256;
      Desede desede0 = new Desede(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "n1Q");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Decrypt;
      desede0.setOperationMode(encDecRyptor__Operation0);
      EncDecRyptor._CipherOperation encDecRyptor__CipherOperation0 = EncDecRyptor._CipherOperation.dofinal;
      byte[] byteArray0 = desede0.process("n1Q", encDecRyptor__CipherOperation0);
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      EncDecRyptor._CIPHER_MODE encDecRyptor__CIPHER_MODE0 = EncDecRyptor._CIPHER_MODE.CBC;
      EncDecRyptor._CIPHER_SIZE encDecRyptor__CIPHER_SIZE0 = EncDecRyptor._CIPHER_SIZE._192;
      Desede desede0 = new Desede(encDecRyptor__CIPHER_MODE0, encDecRyptor__CIPHER_SIZE0, "y]L8n");
      EncDecRyptor._Operation encDecRyptor__Operation0 = EncDecRyptor._Operation.Decrypt;
      desede0.setOperationMode(encDecRyptor__Operation0);
  }
}
