/*
 * This file was automatically generated by EvoSuite
 * Mon May 14 15:37:54 GMT 2018
 */

package com.rac021.jax.api.root;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rac021.jax.api.root.RestConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RestConfig_ESTest extends RestConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RestConfig restConfig0 = new RestConfig();
  }
}
